---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
vagrant:
  raw_config_args:
    - "ssh.insert_key = false"
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 1024
        cpus: 1
platforms:
  - name: centos7
    box: centos/7
    groups:
      - rhel_family
      - python2
  - name: ubuntu18
    box: ubuntu/bionic64
    groups:
      - debian_family
      - python3
lint:
  name: yamllint
  options:
    config-file: .yamllint
provisioner:
  name: ansible
  log: False
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: "/usr/bin/python3"
      python2:
        ansible_python_interpreter: "/usr/bin/python"
      rhel_family:
        os_info_path: "/opt/centos"
      debian_family:
        os_info_path: "/opt/debian"
  playbooks:
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: ansible
  lint:
    name: ansible-lint
