---
- name: Ensure Pip is installed.
  apt:
    name: "{{ pip_package }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  loop:
    - name: cowsay
  become: true
